import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';
import ScrollList from 'components/ScrollList';

export type Planet = {
  name: string;
  diameter: string;
  rotation_period: string;
  orbital_period: string;
  gravity: string;
  population: string;
  climate: string;
  terrain: string;
  surface_water: string;
  residents: string[];
  films: string[];
  url: string;
  created: string;
  edited: string;
};

export interface PlanetList {
  count: number;
  next: string | null;
  previous: string | null;
  results: Planet[];
}

const MainStyled = styled.main`
  align-items: center;
  display: flex;
  flex: 1;
  flex-direction: column;
  font-family: monospace;
  min-height: 100vh;
  padding: 4rem 0;
`;

const Home: NextPage<PlanetList> = (props) => {
  const { results } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyled>
        <h1 className="text-4xl font-bold mb-8 text-white">Planet List</h1>
        <ScrollList initialData={results} />
      </MainStyled>
    </div>
  );
};

export const getServerSideProps = async () => {
  const API_URL = 'https://swapi.dev/api/planets';
  const response = await fetch(API_URL);
  const initialData = await response.json();

  console.log('count :', initialData.results.length);

  return {
    props: initialData
  };
};

export default Home;
