import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';
import { ScrollList } from 'components';
import HeartFilled from '../assets/svgs/heart-solid.svg';
import Image from 'next/image';
import { useRouter } from 'next/router';

export type Planet = {
  name: string;
  diameter: string;
  rotation_period: string;
  orbital_period: string;
  gravity: string;
  population: string;
  climate: string;
  terrain: string;
  surface_water: string;
  residents: string[];
  films: string[];
  url: string;
  created: string;
  edited: string;
};

export interface PlanetList {
  count: number;
  next: string | null;
  previous: string | null;
  results: Planet[];
}

export const MainStyled = styled.main`
  align-items: center;
  display: flex;
  flex: 1;
  flex-direction: column;
  font-family: monospace;
  min-height: 100vh;
  padding: 4rem 0;
`;

const WishListButton = styled.button`
  align-items: center;
  background-color: rgb(21, 128, 61);
  border-radius: 1rem;
  color: white;
  display: flex;
  gap: 8px;
  justify-content: center;
  padding: 1rem;
  position: absolute;
  right: 4rem;
  transition-duration: 150ms;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  :hover {
    background-color: rgb(22, 163, 74);
  }
`;

const Home: NextPage<PlanetList> = (props) => {
  const { results } = props;

  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyled>
        <WishListButton onClick={() => router.push('/wishlist')}>
          <Image src={HeartFilled} alt="My SVG Icon" width={12} height={12} />
          Your Wishlist
        </WishListButton>
        <h1 className="transition text-6xl font-bold mb-8 text-white">Planet List</h1>
        <ScrollList initialData={results} initialNextUrl={props.next} />
      </MainStyled>
    </div>
  );
};

export const getServerSideProps = async () => {
  const API_URL = 'https://swapi.dev/api/planets';
  const response = await fetch(API_URL);
  const initialData = await response.json();

  console.log('count :', initialData.results.length);

  return {
    props: initialData
  };
};

export default Home;
